### ISSUE TITLE
Please ensure you are cleaning up open handles and memory correctly in error cases!

### ISSUE THREAD

**Issue by Daniel-Nashed** [dpastov/DominoReplicationHistoryCleaner#1]
https://github.com/dpastov/DominoReplicationHistoryCleaner/blob/68d7b23227b4f66c1e4c512732e5e3f6d328a348/Demo.lss#L94

Providing code in public with LS2CAPI should have always correct error checking.  
At least in this one case you would leave an open DBHANDLE when an error occurs.

Error checking is essential in C-API! Not doing it right can cause major issues.  
Also others who don't know the C-API well can get the impression that it is easy to modify existing examples or take code as it is and expect it always to work.  

The referenced case can causes a handle leek in an error situation.

It important to only cleanup what you opened/allocated and cleanup what you allocated in any error case!

Thanks

Daniel

PS: Your blog example does not contain any error checking at all and is misleading! 
Without checking the GitHub repo someone could take that code and think it is complete for what they need.

**Comment by dpastov** [comment]
@Daniel-Nashed thanks for pointing out the case with potential memory leak. It's fixed. It seems that you "eat a dog" on that :-)

It's not a point to give a full solution on my blog as people suppose to check solution on GitHub (and there is a link to it at the bottom of the article). I better keep updated only 1 place and it suppose to be GitHub.

**Comment by Daniel-Nashed** [comment]
Your GitHub code has missing error checks as indicated in the reference I posted.
ALL C-API calls need proper error checking.

**Comment by dpastov** [comment]
Hm, could you please show me an example? I probably do not see what you mean. I thought I have an error handling after each use of API.

![image](https://user-images.githubusercontent.com/844872/141748010-49f5148e-44d3-425e-b147-8a7be2e98823.png)

**Comment by Daniel-Nashed** [comment]
you are checking the error and print it after clearing the replication history. but the Error function raises an error and you will not reach the NSFDbClose statement. 
so you have a handle leak in case of error.

**Comment by dpastov** [comment]
@Daniel-Nashed but I have fixed it this morning (I guess u have not seen that) by moving NSFDbClose at the end (and it will always be run).

![image](https://user-images.githubusercontent.com/844872/141752276-aeec6350-bbd4-421b-bf54-efe1714b79ec.png)
